### ISSUE TITLE
Jumping mechanic is unnatual, function needs to be redone.

### ISSUE THREAD

**Issue by aarroz** [aarroz/wwgame#2]
When holding down the "Jump" function, the character will move up and slow down until it falls back down. This is an unnatural form of movement that needs to be re-done in the future.

**Comment by StripedMonkey** [comment]
Changing the jump function to add velocity instead of directly moving the character up would add a more realistic jump however the problem that I ran into is that if you hold the spacebar you constantly go upwards. I need to figure out how to detect whether or not the player is on the ground.

**Comment by aarroz** [comment]
Fixed in commit 9958bff
